// apps/desktop/src/components/new-project-modal.svelte
<script lang="ts">
	import { ProjectsService } from '$lib/projects/projects-service';
	import { IconFolderOpen } from '@tabler/icons-svelte';
	import { getContext } from 'svelte';
	import type { ChangeEventHandler } from 'svelte/elements';

	type Props = {
		open: boolean;
	};
	let { open = $bindable() }: Props = $props();
	const projectsService = getContext<ProjectsService>(ProjectsService);

	const defaultPath = '~/TablixProjects/';
	let form = $state({
		name: '',
		path: defaultPath,
	});

	const onClose = () => {
		open = false;
	};
	const onOk = async () => {
		if (!form.name || !form.path) return;
		await projectsService.addProject(form);
		open = false;
	};
	const onOpen = async () => {
		const path = await projectsService.getValidPath();
		if (!path) return;
		form.path = projectsService.getRelativePath(path);
		form.name ||= path.split('/').at(-1) ?? '';
	};
	const onNameChange: ChangeEventHandler<HTMLInputElement> = (e) => {
		if (form.path && form.path.indexOf(defaultPath) === -1) return;
		form.path = defaultPath + e.currentTarget.value;
	};
</script>

<dialog class="modal" {open}>
	<div class="modal-box max-w-fit">
		<h3 class="text-sm font-bold text-center">New Project</h3>
		<div class="modal-action flex flex-col w-sm">
			<p class="text-sm">Enter new project name:</p>
			<input
				type="text"
				class="input w-full project-input"
				bind:value={form.name}
				oninput={onNameChange}
			/>
			<p class="text-sm">*Enter path:</p>
			<div class="join">
				<input
					required
					type="text"
					class="input w-full join-item validator project-input"
					bind:value={form.path}
				/>
				<button class="btn join-item" onclick={onOpen}>
					<IconFolderOpen class="size-4" />
				</button>
			</div>
			<div class="flex justify-end gap-2">
				<button class="btn btn-sm" onclick={onClose}>Close</button>
				<button class="btn btn-sm" onclick={onOk}>Ok</button>
			</div>
		</div>
	</div>
</dialog>

<style>
	.project-input {
		outline: none;
	}
</style>

// apps/desktop/src/pages/Welcome/NewProjectModal.tsx
import { projectsService } from "@/services/projects";
import {
	Button,
	Dialog,
	Field,
	Group,
	Input,
	Portal,
	Stack,
} from "@chakra-ui/react";
import { IconFolderOpen } from "@tabler/icons-react";
import { useForm } from "@tanstack/react-form";
import type { FormEventHandler } from "react";
import { z } from "zod/v4";

type Props = {
	open: boolean;
	close: () => void;
};
const formSchema = z.object({
	name: z.string().trim().max(128, "Too long").nonempty("Required"),
	path: z.string(),
});

export function NewProjectModal({ close: _close, open }: Props) {
	const defaultPath = "~/TablixProjects/";
	const form = useForm({
		defaultValues: {
			name: "",
			path: defaultPath,
		},
		validators: {
			onChange: formSchema,
		},
		onSubmit: async ({ value }) => {
			const success = await projectsService.addProject(value);
			if (!success) return;
			close();
		},
	});

	const close = () => {
		form.reset();
		_close();
	};

	const onOpen = async () => {
		let path = await projectsService.getValidPath();
		if (!path) return;
		if (!path.endsWith("/")) {
			path += "/";
		}
		onNameChange(undefined, projectsService.getRelativePath(path));
	};
	const onNameChange = (name?: string, path?: string) => {
		const localName = name ?? form.getFieldValue("name");
		const localPath = path ?? form.getFieldValue("path");
		const parts = localPath.split("/");
		const result = `${parts.slice(0, -1).join("/")}/${localName}`;
		form.setFieldValue("path", result);
	};

	const onSubmit: FormEventHandler = (e) => {
		e.preventDefault();
		e.stopPropagation();
		form.handleSubmit();
	};

	return (
		<Dialog.Root lazyMount open={open} placement="center">
			<Portal>
				<Dialog.Backdrop />
				<Dialog.Positioner>
					<Dialog.Content>
						<Dialog.Header>
							<Dialog.Title>New Project</Dialog.Title>
						</Dialog.Header>
						<form onSubmit={onSubmit}>
							<Dialog.Body>
								<Stack gap="4">
									<form.Field
										name="name"
										children={(field) => (
											<Field.Root invalid={!field.state.meta.isValid} required>
												<Field.Label>
													<Field.RequiredIndicator />
													Enter new project name:
												</Field.Label>
												<Input
													type="text"
													autoCorrect="off"
													autoComplete="off"
													value={field.state.value}
													onBlur={field.handleBlur}
													name={field.name}
													onChange={(e) => {
														onNameChange(e.target.value);
														field.handleChange(e.target.value.trim());
													}}
													outline="none"
													required
												/>
												<Field.ErrorText>
													{field.state.meta.errors
														.map((error) => error?.message)
														.join(",")}
												</Field.ErrorText>
											</Field.Root>
										)}
									/>
									<form.Field
										name="path"
										children={(field) => (
											<Field.Root invalid={!field.state.meta.isValid}>
												<Field.Label>Enter root directory:</Field.Label>
												<Group attached width="full">
													<Input
														type="text"
														autoCorrect="off"
														autoComplete="off"
														value={field.state.value}
														onBlur={field.handleBlur}
														name={field.name}
														onChange={(e) => field.handleChange(e.target.value)}
														disabled
													/>
													<Button
														variant="outline"
														outline="none"
														onClick={onOpen}
													>
														<IconFolderOpen className="size-4" />
													</Button>
												</Group>
												<Field.ErrorText>
													{field.state.meta.errors
														.map((error) => error?.message)
														.join(",")}
												</Field.ErrorText>
											</Field.Root>
										)}
									/>
								</Stack>
							</Dialog.Body>
							<Dialog.Footer>
								<form.Subscribe
									selector={(state) => [state.canSubmit, state.isSubmitting]}
									children={([canSubmit, isSubmitting]) => (
										<Stack direction="row">
											<Button variant="outline" onClick={close}>
												Close
											</Button>
											<Button
												type="submit"
												variant="outline"
												disabled={!canSubmit}
												loading={isSubmitting}
											>
												Save
											</Button>
										</Stack>
									)}
								/>
							</Dialog.Footer>
						</form>
					</Dialog.Content>
				</Dialog.Positioner>
			</Portal>
		</Dialog.Root>
	);
}
