// apps/desktop/src/features/welcome/components/NewProjectModal.tsx
import { projectsService } from "@/services/projects";
import { Button, Group, Modal, Stack, TextInput } from "@mantine/core";
import { useForm } from "@mantine/form";
import { IconFolderOpen } from "@tabler/icons-react";
import { zod4Resolver } from "mantine-form-zod-resolver";
import { z } from "zod/v4";
import { useProjects } from "../hooks/useProjects";

type Props = {
	open: boolean;
	close: () => void;
};
export const formSchema = z.object({
	name: z.string().trim().max(128, "Too long").nonempty("Required"),
	path: z.string(),
});

type FormValues = z.infer<typeof formSchema>;

export function NewProjectModal({ close, open }: Props) {
	const defaultPath = "~/TablixProjects/";
	const { dispatch } = useProjects();
	const form = useForm({
		initialValues: {
			name: "",
			path: defaultPath,
		},
		validate: zod4Resolver(formSchema),
	});

	const onClose = () => {
		form.reset();
		close();
	};

	const onOpen = async () => {
		let path = await projectsService.getValidPath();
		if (!path) return;
		if (!path.endsWith("/")) {
			path += "/";
		}
		onNameChange(undefined, projectsService.getRelativePath(path));
	};
	const onNameChange = (name?: string, path?: string) => {
		const values = form.getValues();
		const localName = name ?? values.name;
		const localPath = path ?? values.path;
		const parts = localPath.split("/");
		const result = `${parts.slice(0, -1).join("/")}/${localName}`;
		form.setFieldValue("path", result);
	};

	const onSubmit = async (values: FormValues) => {
		const success = await projectsService.addProject(values);
		if (!success) return;
		projectsService.loadAll().then((projects) => {
			dispatch({
				type: "reload",
				payload: projects,
			});
		});
		onClose();
	};

	return (
		<Modal opened={open} onClose={onClose} title="New Project" centered>
			<form onSubmit={form.onSubmit(onSubmit)}>
				<Stack>
					<TextInput
						withAsterisk
						label="Enter new project name:"
						key={form.key("name")}
						{...form.getInputProps("name")}
						onChange={(e) => {
							form.getInputProps("name").onChange(e);
							onNameChange(e.target.value);
						}}
					/>
					<Group align="end" gap="0">
						<TextInput
							disabled
							flex="1"
							label="Enter root directory:"
							autoCorrect="off"
							autoComplete="off"
							radius="4px 0 0 4px"
							key={form.key("path")}
							{...form.getInputProps("path")}
						/>
						<Button variant="default" c="dark.0" radius="0 4px 4px 0" onClick={onOpen}>
							<IconFolderOpen className="size-4" />
						</Button>
					</Group>
				</Stack>
				<Group justify="flex-end" mt="lg">
					<Button type="submit" variant="light" disabled={!form.isValid} loading={form.submitting}>
						Save
					</Button>
				</Group>
			</form>
		</Modal>
	);
}

// apps/desktop/src/components/new-project-modal.svelte
<script lang="ts">
	import { ProjectsService } from '$lib/projects/projects-service';
	import { IconFolderOpen } from '@tabler/icons-svelte';
	import { getContext } from 'svelte';
	import type { ChangeEventHandler } from 'svelte/elements';

	type Props = {
		open: boolean;
	};
	let { open = $bindable() }: Props = $props();
	const projectsService = getContext<ProjectsService>(ProjectsService);

	const defaultPath = '~/TablixProjects/';
	let form = $state({
		name: '',
		path: defaultPath,
	});

	const onClose = () => {
		open = false;
	};
	const onOk = async () => {
		if (!form.name || !form.path) return;
		await projectsService.addProject(form);
		open = false;
	};
	const onOpen = async () => {
		const path = await projectsService.getValidPath();
		if (!path) return;
		form.path = projectsService.getRelativePath(path);
		form.name ||= path.split('/').at(-1) ?? '';
	};
	const onNameChange: ChangeEventHandler<HTMLInputElement> = (e) => {
		if (form.path && form.path.indexOf(defaultPath) === -1) return;
		form.path = defaultPath + e.currentTarget.value;
	};
</script>

<dialog class="modal" {open}>
	<div class="modal-box max-w-fit">
		<h3 class="text-sm font-bold text-center">New Project</h3>
		<div class="modal-action flex flex-col w-sm">
			<p class="text-sm">Enter new project name:</p>
			<input
				type="text"
				class="input w-full project-input"
				bind:value={form.name}
				oninput={onNameChange}
			/>
			<p class="text-sm">*Enter path:</p>
			<div class="join">
				<input
					required
					type="text"
					class="input w-full join-item validator project-input"
					bind:value={form.path}
				/>
				<button class="btn join-item" onclick={onOpen}>
					<IconFolderOpen class="size-4" />
				</button>
			</div>
			<div class="flex justify-end gap-2">
				<button class="btn btn-sm" onclick={onClose}>Close</button>
				<button class="btn btn-sm" onclick={onOk}>Ok</button>
			</div>
		</div>
	</div>
</dialog>

<style>
	.project-input {
		outline: none;
	}
</style>
